### ISSUE TITLE
flag_cc error

### ISSUE THREAD

**Issue by riksarchen** [TianxSky/DiscordStatus#6]
Hello,
I'm getting flag_cc error and if I remove the {FLAG} option in name formats the server will crash. [:flag_cc error:archen 0-0]

`"NameFormat": "{FLAG}{NAME}: {K}-{D}",`

From server console:
```
Jan 17 21:19:41 linuxserver cs2[311646]:    at DiscordStatus.Chores.FormatStats(PlayerInfo playerinfo) in C:\Users\Kai\source\repos\DiscordStatus\Source\Utils\Chores.cs:line 24
Jan 17 21:19:41 linuxserver cs2[311646]:    at DiscordStatus.DiscordStatus.<UpdateAsync>b__22_4(KeyValuePair`2 kv) in C:\Users\Kai\source\repos\DiscordStatus\Source\DiscordStatus.cs:line 119
Jan 17 21:19:41 linuxserver cs2[311646]:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
Jan 17 21:19:41 linuxserver cs2[311646]:    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
Jan 17 21:19:41 linuxserver cs2[311646]:    at DiscordStatus.DiscordStatus.<UpdateAsync>b__22_1() in C:\Users\Kai\source\repos\DiscordStatus\Source\DiscordStatus.cs:line 125

```

**Comment by vixenbelle** [comment]
how you fix that?
